import { ArticleContent } from '../types';

export const cambodiaFintechRegulation: ArticleContent = {
  slug: 'cambodia-fintech-regulation',
  title: 'Cambodia FinTech Regulation: Complete Licensing and Compliance Framework',
  description: 'Comprehensive guide to Cambodia\'s fintech regulatory framework covering NBC licensing categories, GDT tax compliance, AML/CFT requirements, capital requirements, and operational compliance for payment service providers, digital lenders, and insurtech companies.',
  type: 'knowledge',
  cluster: 'compliance',
  publishedAt: '2026-03-25',
  updatedAt: '2026-03-25',
  readingTime: 10,
  schema: 'TechArticle',
  relatedSlugs: ['nbc', 'gdt', 'fintech-license-cambodia', 'cambodia-aml-requirements'],
  lead: 'Cambodia\'s fintech regulatory landscape has transformed dramatically since the National Bank of Cambodia (NBC) issued the landmark Prakas on Payment Service Providers in 2019, establishing a dedicated licensing framework for non-bank financial technology companies. As of 2026, the Kingdom operates one of ASEAN\'s most structured fintech regulatory environments, with clear licensing categories, defined capital requirements, mandatory technology standards, and increasingly rigorous anti-money laundering and combating the financing of terrorism (AML/CFT) obligations. The regulatory framework is primarily governed by the NBC for payments and financial services, the General Department of Taxation (GDT) for tax compliance, the Securities and Exchange Regulator of Cambodia (SERC) for capital markets activities, and the Insurance Regulator of Cambodia (IRC) for insurtech operations. This article provides a complete reference to the licensing requirements, compliance obligations, and regulatory processes that fintech companies must navigate to operate legally in Cambodia.',
  claims: [
    { stat: 'The NBC has issued 37 payment service provider licenses as of Q4 2025, encompassing mobile money operators, payment aggregators, and e-wallet providers, serving approximately 12 million registered users.', source: 'National Bank of Cambodia Financial Stability Report', year: '2025' },
    { stat: 'Cambodia\'s AML/CFT framework achieved a "Largely Compliant" rating on 32 of 40 FATF recommendations in its 2024 mutual evaluation, up from 18 in the 2017 assessment.', source: 'Asia/Pacific Group on Money Laundering Mutual Evaluation Report', year: '2024' },
    { stat: 'Foreign direct investment in Cambodia\'s fintech sector reached USD 285 million in 2024, a 42% increase over 2023, driven primarily by payment services and digital lending platforms.', source: 'Council for the Development of Cambodia Investment Report', year: '2024' },
    { stat: 'The GDT reported that CamInvoice-compliant businesses increased their VAT collection efficiency by 34% within six months of mandatory e-invoicing adoption.', source: 'General Department of Taxation Annual Report', year: '2025' },
    { stat: 'Cambodia\'s banking sector comprises 59 commercial banks, 7 specialized banks, 87 microfinance institutions, and 37 licensed payment service providers, collectively serving approximately 10 million depositors.', source: 'National Bank of Cambodia Annual Supervision Report', year: '2024' },
  ],
  faqs: [
    { question: 'Can a foreign company obtain a fintech license in Cambodia?', answer: 'Yes. The NBC allows 100% foreign ownership of payment service provider companies. Foreign applicants must incorporate a Cambodian legal entity (typically a limited liability company registered with the Ministry of Commerce), meet minimum capital requirements, appoint at least one resident director, and establish a physical office in Cambodia. The licensing process typically takes 6-12 months from application submission to license issuance. CamFinTech provides end-to-end licensing support including company incorporation, capital structuring, and NBC application preparation.' },
    { question: 'What are the penalties for operating a fintech service without a license?', answer: 'Operating payment services, e-money issuance, or digital lending without NBC authorization is a criminal offense under the Banking and Financial Institutions Law. Penalties include fines up to KHR 200 million (approximately USD 50,000), imprisonment of responsible officers for up to 5 years, asset seizure, and permanent disqualification from financial services. The NBC actively monitors unlicensed operations and has shut down over 15 unauthorized payment platforms since 2022.' },
    { question: 'How long does the NBC licensing process take?', answer: 'The standard timeline from complete application submission to license issuance is 6-12 months. The process involves three phases: preliminary assessment (2-3 months), where the NBC reviews the application for completeness; detailed evaluation (3-6 months), including on-site inspection of technology infrastructure, interviews with key personnel, and review of AML/CFT policies; and final approval (1-3 months), where the NBC Board of Directors votes on the application. Incomplete applications or deficient AML/CFT policies are the most common causes of delays.' },
  ],
  sections: [
    {
      heading: 'Regulatory Architecture Overview',
      content: 'Cambodia\'s financial regulatory architecture is anchored by the National Bank of Cambodia (NBC), which serves as both the central bank and the primary prudential regulator for banks, microfinance institutions, and payment service providers. The NBC\'s regulatory authority derives from the Law on the Organization and Conduct of the National Bank of Cambodia (1996, amended 2023) and the Banking and Financial Institutions Law (1999, amended 2023). For fintech companies, the most relevant regulatory instruments are Prakas (ministerial orders) issued by the NBC Governor.\n\nBeyond the NBC, fintech companies must engage with multiple regulatory bodies depending on their activities. The General Department of Taxation (GDT) under the Ministry of Economy and Finance oversees tax registration, CamInvoice compliance, and withholding tax obligations. The Securities and Exchange Regulator of Cambodia (SERC) regulates securities-related fintech activities including equity crowdfunding and digital asset trading. The Insurance Regulator of Cambodia (IRC) supervises insurtech companies offering digital insurance products. The Cambodia Financial Intelligence Unit (CAFIU) under the NBC receives and analyzes suspicious transaction reports.',
      table: {
        caption: 'Cambodia Financial Regulatory Bodies and Fintech Jurisdiction',
        headers: ['Regulator', 'Parent Ministry', 'Fintech Activities Supervised', 'Key Legislation', 'Website'],
        rows: [
          ['NBC', 'Independent', 'Payments, e-money, digital lending, CBDC', 'Banking & FI Law, Prakas on PSPs', 'nbc.gov.kh'],
          ['GDT', 'Ministry of Economy & Finance', 'Tax compliance, e-invoicing', 'Tax Law, CamInvoice Prakas', 'tax.gov.kh'],
          ['SERC', 'Ministry of Economy & Finance', 'Equity crowdfunding, digital securities', 'Securities Law', 'serc.gov.kh'],
          ['IRC', 'Ministry of Economy & Finance', 'Insurtech, digital insurance distribution', 'Insurance Law', 'irc.gov.kh'],
          ['CAFIU', 'NBC', 'AML/CFT compliance, STR filing', 'AML/CFT Law', 'cafiu.gov.kh'],
        ],
      },
    },
    {
      heading: 'Payment Service Provider Licensing Categories',
      content: 'The NBC\'s Prakas on Payment Service Providers (B7-019-344) establishes three categories of payment service licenses, each with distinct scope, capital requirements, and operational constraints. Category 1 licenses authorize the issuance and management of electronic money (e-wallets). Category 2 licenses cover payment processing, aggregation, and gateway services. Category 3 licenses permit money transfer services, including domestic and international remittance.\n\nCategory 1 (E-Money Issuance) is the most capital-intensive, requiring minimum registered capital of KHR 2 billion (approximately USD 500,000) and full segregation of customer funds in trust accounts at NBC-licensed banks. E-money issuers must maintain a 1:1 reserve ratio, meaning every unit of e-money outstanding must be backed by an equivalent amount in the trust account. Category 2 (Payment Processing) requires KHR 1 billion (approximately USD 250,000) in registered capital and is commonly used by payment aggregators, POS terminal providers, and online payment gateways. Category 3 (Money Transfer) requires KHR 1.5 billion (approximately USD 375,000) and imposes additional KYC requirements for cross-border remittance services.\n\nAll three categories require the applicant to demonstrate robust technology infrastructure, disaster recovery capabilities, data residency within Cambodia, and compliance with NBC\'s information security standards. CamFinTech assists companies in determining the appropriate license category and preparing complete applications.',
      table: {
        caption: 'NBC Payment Service Provider License Categories',
        headers: ['Category', 'Scope', 'Min. Capital (KHR)', 'Min. Capital (USD equiv.)', 'Trust Account Required', 'Licenses Issued (Q4 2025)'],
        rows: [
          ['Category 1', 'E-money issuance, wallet operations', '2 billion', '~USD 500,000', 'Yes (1:1 reserve)', '12'],
          ['Category 2', 'Payment processing, aggregation', '1 billion', '~USD 250,000', 'No', '16'],
          ['Category 3', 'Money transfer, remittance', '1.5 billion', '~USD 375,000', 'Yes (operational reserve)', '9'],
        ],
      },
    },
    {
      heading: 'Capital Requirements and Financial Obligations',
      content: 'Beyond minimum registered capital, NBC-licensed fintech companies face ongoing financial obligations designed to ensure solvency and protect consumer funds. All PSP licensees must maintain a capital adequacy ratio (CAR) of at least 15% of risk-weighted assets, calculated quarterly and reported to the NBC. E-money issuers (Category 1) must additionally maintain a liquidity coverage ratio ensuring they can meet all customer redemption requests within 24 hours.\n\nOperational expenses coverage is another key requirement: PSP licensees must demonstrate that their capital base covers at least 6 months of projected operating expenses at all times. If capital falls below this threshold, the NBC issues a supervisory warning and may restrict new customer onboarding until capital is restored. Annual license renewal fees range from KHR 10 million to KHR 50 million depending on the license category and transaction volume.\n\nFintech companies raising capital from foreign investors must comply with the Foreign Investment Law and register their investment with the Council for the Development of Cambodia (CDC). Investment incentives, including tax holidays of up to 6 years and duty-free import of equipment, are available for qualified investment projects. CamFinTech advises fintech companies on structuring their capital raises to maximize CDC investment incentives while meeting NBC capital requirements.',
    },
    {
      heading: 'Anti-Money Laundering and Counter-Terrorism Financing',
      content: 'Cambodia\'s AML/CFT framework is governed by the Law on Anti-Money Laundering and Combating the Financing of Terrorism (2020, amended 2023), which transposes the Financial Action Task Force (FATF) Forty Recommendations into Cambodian law. The NBC enforces AML/CFT compliance for all financial institutions and PSPs through detailed Prakas specifying customer due diligence (CDD), record-keeping, suspicious transaction reporting (STR), and sanctions screening requirements.\n\nFintech companies must implement a risk-based approach to AML/CFT, conducting customer risk assessments at onboarding and periodically thereafter. Standard CDD requires verification of customer identity using government-issued documents (national ID, passport) and collection of address, occupation, and source of funds information. Enhanced Due Diligence (EDD) is mandatory for politically exposed persons (PEPs), high-risk jurisdictions (FATF grey/black list countries), and transactions above KHR 40 million (approximately USD 10,000). Simplified Due Diligence (SDD) is permitted for low-risk, low-value products up to KHR 4 million (approximately USD 1,000).\n\nSuspicious Transaction Reports must be filed with CAFIU within 24 hours of detection. The NBC requires all PSPs to implement automated transaction monitoring systems that flag unusual patterns, including structuring (splitting transactions to avoid thresholds), rapid movement of funds, and transactions involving high-risk jurisdictions. Failure to file STRs carries penalties of up to KHR 100 million and potential license revocation.',
      table: {
        caption: 'AML/CFT Due Diligence Requirements by Risk Level',
        headers: ['CDD Level', 'Trigger', 'ID Requirements', 'Source of Funds', 'Ongoing Monitoring', 'Review Frequency'],
        rows: [
          ['Simplified (SDD)', 'Low-value products < KHR 4M', 'National ID or passport', 'Not required', 'Transaction monitoring', 'Annual'],
          ['Standard (CDD)', 'All customers at onboarding', 'National ID + address proof', 'Self-declaration', 'Transaction monitoring + periodic review', 'Every 2 years'],
          ['Enhanced (EDD)', 'PEPs, high-risk jurisdictions, > KHR 40M', 'National ID + address + occupation', 'Documentary evidence', 'Continuous monitoring + senior management review', 'Every 6 months'],
        ],
      },
    },
    {
      heading: 'Technology and Cybersecurity Standards',
      content: 'The NBC\'s Prakas on Technology Risk Management (B7-020-275) establishes mandatory cybersecurity and technology governance standards for all financial institutions and PSPs. The requirements cover seven domains: IT governance, information security management, cybersecurity operations, data management, technology project management, IT outsourcing, and business continuity planning.\n\nFintech companies must appoint a Chief Information Security Officer (CISO) or equivalent role, conduct annual penetration testing by qualified third parties, implement Security Information and Event Management (SIEM) systems for real-time threat monitoring, and maintain a cyber incident response plan tested through tabletop exercises at least annually. Data must be encrypted at rest (AES-256 or equivalent) and in transit (TLS 1.2+). Multi-factor authentication is mandatory for all administrative access to payment systems.\n\nData residency requirements mandate that all customer data and transaction records be stored on servers physically located within Cambodia. Cloud computing is permitted only if the cloud provider operates a data center within Cambodia or the NBC grants a specific exemption (which is rarely issued). This requirement has significant implications for fintech companies that rely on global cloud providers, as it typically necessitates either a dedicated in-country deployment or partnership with a local hosting provider.\n\nThe NBC conducts on-site technology inspections as part of the licensing process and periodically during the license term. Findings from these inspections must be remediated within 30 days for critical issues and 90 days for non-critical issues.',
    },
    {
      heading: 'Tax Compliance and CamInvoice Integration',
      content: 'All NBC-licensed fintech companies must register with the GDT and comply with Cambodia\'s tax obligations, including corporate income tax (standard rate 20%), value-added tax (10% on taxable supplies), withholding taxes on payments to non-residents (14% on services, 4% on interest), and monthly tax on salaries. Financial services are generally exempt from VAT, but payment processing fees, technology service charges, and consulting fees are taxable.\n\nThe mandatory CamInvoice e-invoicing system adds a significant compliance layer. All invoices issued by fintech companies to merchants, banks, or enterprises must be submitted to CamInvoice in real-time UBL 2.1 format. This includes service fee invoices, technology licensing fees, and any other B2B charges. The CamInvoice API validates each invoice against GDT business rules and returns a digital tax stamp confirming registration. Invoices without valid CamInvoice stamps are not deductible for the buyer\'s corporate income tax purposes, creating strong economic incentives for compliance.\n\nThe GDT has allocated specific Taxpayer Identification Number (TIN) ranges for NBC-licensed PSPs, enabling automated cross-referencing between NBC licensing records and GDT tax filings. CamFinTech assists fintech companies in structuring their tax compliance programs, integrating CamInvoice with their billing systems, and preparing for GDT audits.',
      table: {
        caption: 'Tax Obligations for Fintech Companies in Cambodia',
        headers: ['Tax Type', 'Rate', 'Frequency', 'Due Date', 'Applicable To'],
        rows: [
          ['Corporate Income Tax', '20%', 'Annual', 'March 31 of following year', 'Net profit after deductions'],
          ['Minimum Tax', '1% of turnover', 'Annual', 'March 31 (if CIT < minimum)', 'Gross revenue'],
          ['VAT', '10%', 'Monthly', '20th of following month', 'Taxable services (not financial services)'],
          ['Withholding Tax (services)', '14%', 'Per payment', '20th of following month', 'Payments to non-resident service providers'],
          ['Withholding Tax (interest)', '4%', 'Per payment', '20th of following month', 'Interest paid to non-residents'],
          ['Tax on Salary', '0-20% progressive', 'Monthly', '20th of following month', 'Employee salaries and benefits'],
          ['Patent Tax', 'KHR 1.2-5M', 'Annual', 'March 31', 'Business registration renewal'],
        ],
      },
    },
    {
      heading: 'Digital Lending Regulation',
      content: 'Digital lending has emerged as one of Cambodia\'s fastest-growing fintech segments, prompting the NBC to issue specific guidance on technology-enabled credit products. The Prakas on Lending by Technology (2023) establishes that any entity providing credit through digital channels must hold either a banking license, a microfinance institution (MFI) license, or a specific digital lending endorsement on a PSP license. Unlicensed digital lending is explicitly prohibited and actively enforced.\n\nDigital lenders must comply with the NBC\'s consumer protection requirements, including clear disclosure of all fees and interest rates in annualized percentage rate (APR) format, a mandatory 7-day cooling-off period for first-time borrowers, prohibition of predatory collection practices, and maximum interest rate caps set at 18% per annum for secured loans and 36% per annum for unsecured microloans. The NBC has banned aggressive marketing of credit products via SMS or social media to individuals who have not explicitly opted in.\n\nCredit scoring models used by digital lenders must be registered with the NBC and subject to periodic review for fairness and accuracy. The NBC requires that borrowers be informed of the factors that contributed to their credit decision. Alternative data sources (mobile usage patterns, social media activity, e-commerce transaction history) may be used in credit scoring but must be validated against repayment performance data and must not discriminate based on protected characteristics.\n\nCamFinTech advises digital lending startups on NBC licensing requirements, credit model registration, and consumer protection compliance.',
    },
    {
      heading: 'Sandbox and Innovation Testing Framework',
      content: 'The NBC launched its Regulatory Sandbox in 2023, providing a structured environment for fintech companies to test innovative products and services under regulatory supervision before seeking full licensing. The sandbox allows up to 12 months of testing with a defined scope, limited customer base (maximum 5,000 users), and reduced capital requirements (50% of standard minimums). Successful sandbox graduates receive expedited licensing review.\n\nTo enter the sandbox, applicants must submit a detailed proposal describing the innovative product, target market, technology architecture, risk mitigation measures, and consumer protection safeguards. The NBC evaluates proposals based on genuine innovation (not replication of existing services), potential benefit to financial inclusion, and the applicant\'s technical and managerial capability. As of Q4 2025, the NBC has admitted 8 companies to the sandbox, with 5 successfully graduating to full licenses.\n\nThe sandbox is particularly relevant for fintech models that do not fit neatly into existing license categories, such as decentralized finance (DeFi) applications built on Bakong infrastructure, AI-powered robo-advisory services, open banking data aggregation platforms, and blockchain-based trade finance solutions. CamFinTech helps companies prepare sandbox applications that demonstrate genuine innovation while addressing the NBC\'s risk and consumer protection concerns.',
    },
    {
      heading: 'Foreign Exchange and Cross-Border Regulations',
      content: 'Cambodia\'s foreign exchange regime is relatively liberal compared to regional peers, with no restrictions on current account transactions and limited capital account controls. However, fintech companies dealing in cross-border payments and foreign exchange must comply with specific NBC regulations. The Prakas on Foreign Exchange Reporting requires all transactions above USD 10,000 to be reported to the NBC\'s Statistics Department. Money transfer operators (Category 3 PSPs) must report all cross-border remittances regardless of amount.\n\nThe NBC\'s de-dollarization policy, which aims to increase Khmer Riel usage from approximately 20% to 30% of total money supply by 2030, has regulatory implications for fintech companies. New PSP licenses now require the ability to process both KHR and USD transactions, and the NBC encourages (but does not yet mandate) default pricing in KHR. The Reserve Requirement Regulation imposes higher reserve ratios for USD deposits (12.5%) compared to KHR deposits (7.0%), creating a cost incentive for financial institutions to promote Riel-denominated products.\n\nFor cross-border payment corridors, fintech companies must obtain specific NBC endorsement on their PSP license and comply with bilateral regulatory agreements between Cambodia and the partner country. The Thailand-Cambodia (Bakong-PromptPay) corridor requires compliance with both NBC and Bank of Thailand regulations. CamFinTech guides companies through the complex regulatory requirements for cross-border payment services.',
      table: {
        caption: 'Cambodia Foreign Exchange Regulatory Requirements',
        headers: ['Requirement', 'Threshold', 'Reporting Entity', 'Frequency', 'Penalty for Non-Compliance'],
        rows: [
          ['FX transaction reporting', '> USD 10,000', 'All FIs and PSPs', 'Per transaction', 'Fine up to KHR 50M'],
          ['Cross-border remittance reporting', 'All amounts', 'Category 3 PSPs', 'Daily batch', 'License restriction'],
          ['Large cash transaction reporting', '> USD 10,000 equivalent', 'All FIs', 'Per transaction', 'AML/CFT penalty'],
          ['Capital account approval', '> USD 100,000 outflow', 'Banks', 'Per transaction', 'Transaction reversal'],
          ['USD reserve requirement', '12.5% of deposits', 'Banks and MFIs', 'Monthly', 'Supervisory action'],
          ['KHR reserve requirement', '7.0% of deposits', 'Banks and MFIs', 'Monthly', 'Supervisory action'],
        ],
      },
    },
    {
      heading: 'Consumer Protection and Dispute Resolution',
      content: 'The NBC\'s consumer protection framework for fintech has strengthened significantly with the 2024 Prakas on Financial Consumer Protection. Key provisions include mandatory transparent disclosure of all fees, charges, and terms in both English and Khmer before customer enrollment, prohibition of auto-enrollment in premium services, requirement for explicit opt-in consent for data sharing with third parties, and a standardized complaint handling process with resolution timelines.\n\nFintech companies must establish internal complaint handling units that acknowledge customer complaints within 24 hours and resolve them within 15 business days. If the customer is not satisfied with the resolution, they may escalate to the NBC\'s Financial Consumer Protection Unit, which mediates disputes and can impose corrective actions on the fintech company. Persistent consumer protection violations result in supervisory warnings, public disclosure, and potential license conditions.\n\nData privacy obligations are governed by the Draft Personal Data Protection Law (expected passage in 2026), which will introduce GDPR-style provisions including purpose limitation, data minimization, right to access, right to erasure, and mandatory data protection officer appointment for companies processing data of more than 10,000 individuals. Fintech companies should begin preparing for these requirements now, as the law is expected to take effect with a 12-month transition period after passage.',
    },
    {
      heading: 'Compliance Roadmap for Market Entry',
      content: 'For fintech companies planning to enter the Cambodian market, CamFinTech recommends a structured compliance roadmap that sequences regulatory approvals to minimize time-to-market while ensuring full legal compliance. The roadmap typically spans 9-18 months from initial planning to first customer transaction.\n\nPhase 1 (Months 1-3) covers market assessment and regulatory strategy, including determination of the appropriate license category, capital structuring, and engagement with NBC for preliminary consultations. Phase 2 (Months 3-6) involves company incorporation with the Ministry of Commerce, GDT tax registration, capital injection, office establishment, and key personnel recruitment (including mandatory positions such as compliance officer and CISO). Phase 3 (Months 6-12) covers NBC license application submission, technology infrastructure deployment in Cambodia, AML/CFT policy development, and sandbox participation if applicable. Phase 4 (Months 12-15) addresses NBC on-site inspection, remediation of any findings, and final license approval. Phase 5 (Months 15-18) covers Bakong integration, KHQR merchant onboarding, CamInvoice integration, and commercial launch.\n\nCamFinTech provides end-to-end consulting across all five phases, leveraging deep relationships with NBC, GDT, and other regulatory bodies to ensure smooth and timely approvals. Our clients have achieved average licensing timelines 30% shorter than the industry average through proactive regulatory engagement and thorough application preparation.',
    },
  ],
};
