import { ArticleContent } from '../types';

export const cambodiaScfOpportunity: ArticleContent = {
  slug: 'cambodia-scf-opportunity',
  title: 'Cambodia Supply Chain Finance: Market Opportunity and Technical Architecture',
  description: 'In-depth analysis of Cambodia\'s supply chain finance market opportunity, covering the SME financing gap, CamInvoice-enabled receivables financing, Bakong settlement infrastructure, technical architecture patterns, and investment thesis for SCF platforms.',
  type: 'knowledge',
  cluster: 'investment',
  publishedAt: '2026-03-25',
  updatedAt: '2026-03-25',
  readingTime: 10,
  schema: 'TechArticle',
  relatedSlugs: ['supply-chain-finance', 'caminvoice', 'bakong'],
  lead: 'Cambodia\'s supply chain finance (SCF) market represents one of the most compelling fintech investment opportunities in Southeast Asia, driven by a convergence of structural factors: a USD 4.2 billion SME financing gap identified by the International Finance Corporation, mandatory electronic invoicing through CamInvoice creating a digital audit trail for receivables, real-time payment settlement on Bakong rails enabling instant disbursement, and a garment and agriculture export sector worth USD 22 billion annually that generates massive volumes of trade receivables. Unlike mature markets where SCF platforms must build data connectivity from scratch, Cambodia\'s Government-as-a-Platform infrastructure provides the foundational data layer — verified invoices, real-time payment rails, and digital identity verification — upon which SCF products can be built natively. This article provides a comprehensive analysis of the market opportunity, technical architecture requirements, regulatory landscape, and investment thesis for supply chain finance in Cambodia.',
  claims: [
    { stat: 'The International Finance Corporation estimates Cambodia\'s SME financing gap at USD 4.2 billion, with approximately 70% of formal SMEs reporting access to finance as their primary growth constraint.', source: 'International Finance Corporation MSME Finance Gap Database', year: '2024' },
    { stat: 'Cambodia\'s garment and textile sector, the country\'s largest export industry, generated USD 11.4 billion in exports in 2024, employing approximately 700,000 workers across 1,100 factories.', source: 'Garment Manufacturers Association in Cambodia', year: '2024' },
    { stat: 'Average payment terms in Cambodia\'s garment supply chain are 90-120 days from invoice to settlement, with Tier 2 and Tier 3 suppliers reporting average DSO (Days Sales Outstanding) of 105 days.', source: 'Asian Development Bank Supply Chain Finance Study', year: '2024' },
    { stat: 'The World Bank projects Cambodia\'s GDP to grow at 6.1% in 2026, with the industrial sector (including manufacturing and construction) contributing 38% of GDP growth.', source: 'World Bank Cambodia Economic Update', year: '2025' },
    { stat: 'Only 18% of Cambodia\'s registered SMEs have access to formal bank credit, compared to 43% in Thailand and 38% in Vietnam, representing a structural opportunity for alternative financing models.', source: 'Asian Development Bank Financial Inclusion Study', year: '2024' },
  ],
  faqs: [
    { question: 'What makes Cambodia\'s SCF opportunity unique compared to other ASEAN markets?', answer: 'Cambodia is the only ASEAN market where mandatory electronic invoicing (CamInvoice), real-time CBDC payment settlement (Bakong), and digital identity verification (CamDigiKey) are all government-operated, interoperable, and available as platform APIs. This means SCF providers can verify invoices against GDT records in real time, confirm buyer creditworthiness through CamDX data, and disburse funds instantly via Bakong — capabilities that require years of private infrastructure building in Thailand, Vietnam, or Indonesia. The combination of a large financing gap and ready-made digital infrastructure creates a uniquely favorable environment for SCF innovation.' },
    { question: 'What regulatory license is needed to offer supply chain finance in Cambodia?', answer: 'SCF platforms that provide financing (factoring, reverse factoring, or invoice discounting) require an NBC license. If the SCF platform purchases receivables (factoring), it typically needs a microfinance institution (MFI) license or a banking license. If it operates as a marketplace connecting lenders to borrowers, it may qualify for a Category 2 PSP license with a specific endorsement. The NBC evaluates SCF business models on a case-by-case basis. CamFinTech assists SCF companies in determining the appropriate licensing path and preparing regulatory applications.' },
    { question: 'How does CamInvoice enable supply chain finance?', answer: 'CamInvoice creates a verified, government-stamped digital record of every B2B invoice. SCF platforms can use the CamInvoice API to verify that an invoice is genuine (not fabricated), has not been previously financed (preventing double-financing fraud), and has been accepted by the buyer. This government-verified invoice data dramatically reduces credit risk assessment costs and enables automated underwriting. The CamInvoice digital stamp serves as a trust anchor that replaces the manual invoice verification processes used in traditional factoring.' },
    { question: 'What returns can investors expect from Cambodia SCF platforms?', answer: 'Cambodia SCF platforms typically charge discount rates of 1.5-3.0% per month for receivables financing, reflecting the high risk premium for SME credit in a developing market. Net yields to investors after platform fees and credit losses range from 12-18% annualized in USD-denominated programs and 15-22% in KHR-denominated programs. These returns are attractive compared to bank deposit rates of 4-6% and reflect the genuine credit risk and liquidity premium of the market. However, investors should note that Cambodia\'s credit bureau coverage is limited and historical default data for SCF products is sparse.' },
  ],
  sections: [
    {
      heading: 'The SME Financing Gap',
      content: 'Cambodia\'s small and medium enterprise sector forms the backbone of the national economy, comprising approximately 520,000 registered businesses that contribute 58% of GDP and employ 72% of the non-agricultural workforce. Despite their economic significance, Cambodian SMEs face severe constraints in accessing formal finance. The International Finance Corporation\'s MSME Finance Gap Database estimates the unmet financing need at USD 4.2 billion, making Cambodia\'s gap the largest in ASEAN relative to GDP.\n\nThe root causes of the financing gap are structural. Cambodia\'s banking sector, while profitable, operates with conservative underwriting practices that favor collateral-backed lending. Approximately 85% of bank loans to SMEs require land title collateral, effectively excluding businesses that lack real estate assets. Microfinance institutions (MFIs) fill part of the gap but charge interest rates of 12-24% per annum, which are prohibitive for thin-margin businesses in manufacturing and agriculture. Invoice-based financing — where receivables serve as collateral instead of land — remains underdeveloped, with less than USD 200 million in outstanding factoring volume compared to over USD 3 billion in Thailand.\n\nSupply chain finance addresses this gap by using the creditworthiness of large buyers (anchor corporates) rather than the SME\'s own balance sheet to underwrite financing. When a garment factory receives a purchase order from H&M or Walmart, the credit risk is effectively the buyer\'s, not the factory\'s. SCF platforms that can verify invoices, confirm buyer payment history, and disburse funds in real time can serve this market at lower cost and higher volume than traditional bank lending.',
    },
    {
      heading: 'Key Supply Chain Verticals',
      content: 'Cambodia\'s SCF opportunity concentrates in four primary supply chain verticals, each with distinct characteristics, stakeholders, and financing requirements. The garment and textile sector is the largest, generating USD 11.4 billion in annual exports and involving approximately 1,100 factories that source from thousands of domestic Tier 2 and Tier 3 suppliers. The agriculture sector, including rice, cassava, rubber, and cashew nuts, generates USD 4.8 billion in exports and involves a fragmented supply chain of smallholder farmers, aggregators, and processors. The construction sector contributes USD 4.3 billion to GDP and involves complex supply chains for building materials, equipment, and subcontractor services. The tourism and hospitality sector, generating USD 3.2 billion in revenue, involves hotel supply chains for food, beverages, linen, and maintenance services.\n\nEach vertical presents different SCF product requirements. Garment supply chains need pre-shipment financing (purchase order finance) and post-shipment financing (receivables factoring) with 60-120 day tenors. Agriculture supply chains need harvest financing with seasonal patterns and commodity price hedging. Construction supply chains need progress payment financing tied to project milestones. Understanding these vertical-specific requirements is essential for designing effective SCF products.',
      table: {
        caption: 'Cambodia Supply Chain Finance Addressable Market by Vertical',
        headers: ['Vertical', 'Annual Volume (USD B)', 'Avg. Payment Terms', 'Estimated SCF Addressable (USD M)', 'Key Anchors', 'Financing Gap Severity'],
        rows: [
          ['Garment & Textile', '11.4', '90-120 days', '1,800', 'H&M, Walmart, Adidas, GAP', 'Critical'],
          ['Agriculture', '4.8', '60-90 days', '720', 'Amru Rice, Olam, Mong Reththy', 'Severe'],
          ['Construction', '4.3', '30-60 days', '430', 'OCIC, Chip Mong, BooyoungKhmer', 'Moderate'],
          ['Tourism & Hospitality', '3.2', '30-45 days', '320', 'Sokha Hotels, NagaCorp, Rosewood', 'Moderate'],
          ['Total Addressable', '23.7', '—', '3,270', '—', '—'],
        ],
      },
    },
    {
      heading: 'CamInvoice as the Trust Anchor',
      content: 'The mandatory CamInvoice electronic invoicing system fundamentally changes the economics of supply chain finance in Cambodia by providing a government-verified, tamper-proof digital record of every B2B transaction. Before CamInvoice, invoice verification was the most expensive and time-consuming step in the factoring process, requiring manual document review, buyer confirmation calls, and site visits to verify delivery. CamInvoice automates this entire process.\n\nWhen a supplier submits an invoice through CamInvoice, the GDT\'s system validates the invoice against its business rules, checks that both seller and buyer TINs are valid and active, applies a unique invoice reference number, and returns a digitally signed tax stamp. This stamp serves as government attestation that the invoice is genuine and has been recorded in the national tax system. SCF platforms can query the CamInvoice API using the invoice reference to verify authenticity, confirm that the invoice has not been previously pledged as collateral (preventing double-financing fraud), and retrieve the invoice details including amount, currency, payment terms, and buyer identity.\n\nThis government-verified invoice data eliminates the information asymmetry that traditionally makes SME receivables financing expensive. SCF platforms can automate underwriting decisions based on verified invoice data combined with buyer payment history from Bakong settlement records, reducing the cost of credit assessment from days to seconds and enabling micro-financing of individual invoices rather than portfolio-level facilities.',
    },
    {
      heading: 'Technical Architecture for SCF Platforms',
      content: 'A production-grade SCF platform operating on Cambodia\'s GaaP infrastructure requires integration with four systems: CamInvoice for invoice verification, Bakong for payment settlement, CamDigiKey for supplier and buyer identity verification, and CamDX for supplementary business data (company registration, tax clearance status). The recommended architecture follows an event-driven microservices pattern where each GaaP integration is encapsulated in a dedicated service.\n\nThe Invoice Verification Service connects to the CamInvoice API to ingest verified invoices, validate their authenticity, check for prior pledge status, and store normalized invoice data in the platform\'s data warehouse. The Payment Service integrates with Bakong through a bank partner API to handle financing disbursements to suppliers and repayment collections from buyers. The Identity Service uses CamDigiKey for supplier and buyer onboarding and periodic re-verification. The Data Enrichment Service queries CamDX for business registration details, tax compliance status, and other regulatory data points used in credit scoring.\n\nThe Credit Engine sits at the center, consuming data from all four services to make automated financing decisions. It evaluates each invoice based on buyer creditworthiness (payment history, financial statements), supplier track record (repayment history, invoice volume), invoice characteristics (amount, tenor, industry), and portfolio concentration limits. CamFinTech has developed reference architecture blueprints and can provide technical consulting for SCF platform development.',
      table: {
        caption: 'SCF Platform Technical Architecture Components',
        headers: ['Component', 'GaaP Integration', 'Function', 'Data Flow', 'Latency Requirement'],
        rows: [
          ['Invoice Verification Service', 'CamInvoice API', 'Validate invoice authenticity, check pledge status', 'Real-time query', '< 3 seconds'],
          ['Payment Service', 'Bakong (via bank API)', 'Disburse financing, collect repayments', 'Event-driven', '< 5 seconds'],
          ['Identity Service', 'CamDigiKey (OIDC)', 'Onboard and verify suppliers/buyers', 'On-demand', '< 10 seconds'],
          ['Data Enrichment Service', 'CamDX (mTLS)', 'Business registration, tax status', 'Batch + on-demand', '< 30 seconds'],
          ['Credit Engine', 'Internal', 'Automated underwriting decisions', 'Event-driven', '< 2 seconds'],
          ['Reconciliation Engine', 'Bakong + CamInvoice', 'Match payments to invoices', 'Daily batch', 'T+1'],
        ],
      },
    },
    {
      heading: 'Credit Risk and Underwriting Models',
      content: 'Designing effective credit risk models for Cambodia\'s SCF market requires navigating limited historical data, low credit bureau coverage, and structural features unique to the Cambodian economy. The Credit Bureau of Cambodia (CBC), established in 2012, covers approximately 4.5 million borrower records, primarily from bank and MFI lending. However, coverage of SME trade credit and payables data is minimal, meaning that traditional credit scoring approaches based on bureau data are insufficient for SCF underwriting.\n\nEffective SCF credit models in Cambodia must rely heavily on transactional data from GaaP infrastructure. Key data points include: buyer payment history on Bakong rails (average days to pay, payment consistency, returned payment frequency), CamInvoice transaction volumes (monthly invoice count, average invoice size, buyer diversity), CamDX business data (years in operation, registered capital, tax compliance status), and platform-specific data (prior financing repayment history, early payment frequency).\n\nCamFinTech recommends a hybrid scoring approach that combines rule-based filters (minimum buyer credit quality, maximum single-invoice exposure, maximum buyer concentration) with machine learning models trained on platform transaction data as volume accumulates. Initial underwriting should be conservative, focusing on receivables from investment-grade multinational buyers (e.g., major garment brands) where buyer default risk is negligible. As the platform accumulates repayment data, models can be expanded to cover domestic buyers with shorter track records.\n\nExpected loss rates for Cambodia SCF vary significantly by buyer quality: 0.5-1.5% for multinational anchor buyers, 2-4% for large domestic corporates, and 5-10% for mid-market domestic buyers. SCF platforms should price financing to achieve a net interest margin of 8-12% after expected losses.',
    },
    {
      heading: 'Regulatory Landscape for SCF',
      content: 'The regulatory framework for supply chain finance in Cambodia is evolving but currently lacks a dedicated SCF regulatory category. SCF platforms must navigate existing NBC licensing categories and work with regulators to classify their specific business model. The NBC evaluates SCF business models based on the core activity: if the platform purchases receivables (true-sale factoring), it is classified as a lending activity requiring an MFI or banking license; if it operates as a marketplace connecting institutional lenders to verified receivables, it may qualify for a Category 2 PSP license with an endorsement.\n\nThe NBC issued a Circular on Supply Chain Finance Guidelines in late 2024, providing initial guidance on accounting treatment, capital requirements, and risk management standards for SCF activities. Key provisions include: receivables purchased through true-sale factoring must be recognized on the SCF provider\'s balance sheet and provisioned according to NBC loan classification rules; marketplace platforms must maintain a minimum guarantee fund equal to 5% of outstanding financed receivables; and all SCF providers must implement real-time CamInvoice verification for every financed invoice.\n\nThe Securities and Exchange Regulator of Cambodia (SERC) may also have jurisdiction if SCF platforms issue securities backed by receivables pools (asset-backed securities or receivables-backed notes). CamFinTech advises SCF companies on regulatory classification and maintains ongoing dialogue with the NBC on evolving SCF regulation.',
      table: {
        caption: 'Regulatory Requirements for SCF Business Models',
        headers: ['SCF Model', 'Regulatory Classification', 'License Required', 'Capital Requirement', 'Key Compliance Obligations'],
        rows: [
          ['Direct Factoring', 'Lending activity', 'MFI or Bank license', 'KHR 10-30 billion', 'Loan classification, provisioning, NBC reporting'],
          ['Reverse Factoring', 'Lending activity', 'MFI or Bank license', 'KHR 10-30 billion', 'Loan classification, buyer credit assessment'],
          ['SCF Marketplace', 'Payment facilitation', 'Category 2 PSP + endorsement', 'KHR 1 billion + 5% guarantee fund', 'Investor protection, platform risk management'],
          ['Invoice Discounting', 'Lending activity', 'MFI license', 'KHR 10 billion', 'NBC prudential reporting, AML/CFT'],
          ['Purchase Order Finance', 'Lending activity', 'MFI or Bank license', 'KHR 10-30 billion', 'Collateral management, NBC reporting'],
        ],
      },
    },
    {
      heading: 'Garment Supply Chain Deep Dive',
      content: 'The garment and textile sector deserves special attention as Cambodia\'s largest SCF opportunity. The industry operates through a tiered supply chain: Tier 1 manufacturers (cut-make-trim factories) receive orders from international brands and retailers. Tier 2 suppliers provide fabric, thread, zippers, buttons, and packaging to Tier 1 factories. Tier 3 suppliers provide raw materials, chemicals, and ancillary services to both Tier 1 and Tier 2 entities.\n\nPayment flows in the garment supply chain create a cash flow squeeze that SCF directly addresses. International buyers typically pay Tier 1 factories on 60-90 day terms after shipment. Tier 1 factories pay their Tier 2 suppliers on 30-60 day terms. Tier 2 suppliers pay Tier 3 on 15-30 day terms. However, the total cycle from raw material purchase to final payment from the international buyer can exceed 150 days. Tier 2 and Tier 3 suppliers, which are typically SMEs with limited working capital, bear the brunt of this cash flow gap.\n\nSCF platforms targeting the garment supply chain can offer reverse factoring programs anchored by creditworthy international buyers. In this model, the buyer approves invoices from its suppliers, the SCF platform finances the approved invoices at a discount rate reflecting the buyer\'s credit quality (not the supplier\'s), and the buyer pays the SCF platform at the original maturity date. Because the credit risk is effectively the international buyer\'s, discount rates can be as low as 1.5-2.0% per month, significantly cheaper than the 18-24% annual rates SMEs pay for traditional bank loans.\n\nThe Garment Manufacturers Association in Cambodia (GMAC) has expressed support for SCF platforms that improve supplier liquidity and supply chain stability.',
    },
    {
      heading: 'Bakong Settlement Integration for SCF',
      content: 'Bakong\'s real-time settlement capability transforms the disbursement and collection process for SCF platforms. Traditional factoring in Cambodia relies on bank wire transfers that settle in T+1 or T+2, creating a delay between financing approval and fund availability that reduces the value proposition for suppliers. Bakong enables instant disbursement: once the credit engine approves an invoice for financing, the platform can disburse funds to the supplier\'s Bakong-connected bank account within seconds.\n\nThe SCF platform\'s payment service integrates with Bakong through a bank partner API, using the standard payment initiation flow. For disbursements, the platform submits a payment request with the supplier\'s Bakong account identifier, the financing amount (invoice face value minus the discount), and a reference linking the payment to the specific invoice. Settlement confirmation arrives via webhook, typically within 2 seconds. The platform records the settlement confirmation and updates the invoice status to "Financed."\n\nFor collections, the platform monitors the buyer\'s payment against the original invoice. When the buyer pays via Bakong (which is increasingly common as KHQR adoption grows), the platform receives a settlement notification and automatically matches the payment to the financed invoice. If the buyer pays through non-Bakong channels (bank wire, check), reconciliation requires manual matching against the bank partner\'s daily settlement file.\n\nCamFinTech recommends SCF platforms incentivize Bakong-based buyer payments by offering slightly better financing terms for invoices where the buyer commits to Bakong settlement, simplifying reconciliation and reducing operational costs.',
    },
    {
      heading: 'Investment Thesis and Market Sizing',
      content: 'The investment thesis for Cambodia SCF rests on four structural pillars. First, the financing gap is large and growing: USD 4.2 billion in unmet SME financing demand with formal credit penetration at only 18% of registered SMEs. Second, the GaaP infrastructure dramatically reduces the cost of building SCF technology: CamInvoice provides verified invoice data, Bakong provides real-time settlement, and CamDigiKey provides identity verification — all as platform APIs. Third, regulatory momentum is favorable: the NBC actively encourages SCF innovation as a solution to the SME financing gap. Fourth, Cambodia\'s export economy generates massive receivables volume: USD 22 billion in annual exports creates a deep pool of financeable trade receivables.\n\nMarket sizing analysis based on total export volume, average payment terms, and typical SCF penetration rates in comparable markets suggests a total addressable market (TAM) of approximately USD 3.3 billion in annual SCF volume. At mature-market penetration rates (15-20% of eligible receivables), the serviceable addressable market (SAM) is USD 500-660 million. At early-market penetration rates (3-5%), the near-term serviceable obtainable market (SOM) is USD 100-165 million annually.\n\nRevenue potential for an SCF platform processing USD 100 million in annual volume at an average discount rate of 2.0% per month and average tenor of 60 days yields approximately USD 4 million in annual gross revenue. After funding costs (5-8% annual cost of capital), credit losses (1-3%), and operating expenses, net margins of 20-35% are achievable at scale.',
      table: {
        caption: 'Cambodia SCF Market Sizing (2026 Estimates)',
        headers: ['Metric', 'Conservative', 'Base Case', 'Optimistic', 'Basis'],
        rows: [
          ['Total Addressable Market (TAM)', 'USD 2.5B', 'USD 3.3B', 'USD 4.2B', 'Export receivables + domestic B2B'],
          ['SCF Penetration Rate', '3%', '5%', '8%', 'Comparable market benchmarks'],
          ['Serviceable Obtainable Market (SOM)', 'USD 75M', 'USD 165M', 'USD 336M', 'TAM x penetration rate'],
          ['Avg. Discount Rate (monthly)', '1.5%', '2.0%', '2.5%', 'Market pricing analysis'],
          ['Avg. Financing Tenor', '45 days', '60 days', '90 days', 'Payment terms analysis'],
          ['Annual Gross Revenue (at SOM)', 'USD 1.7M', 'USD 6.6M', 'USD 25.2M', 'SOM x rate x turnover'],
          ['Expected Credit Loss Rate', '3%', '2%', '1%', 'Buyer quality mix'],
          ['Net Margin (at scale)', '20%', '28%', '35%', 'Comparable platform benchmarks'],
        ],
      },
    },
    {
      heading: 'Competitive Landscape and Market Entry Strategy',
      content: 'Cambodia\'s SCF market is nascent, with limited competition from established players. The major commercial banks (ACLEDA, ABA, Canadia, BRED) offer traditional trade finance products (letters of credit, bank guarantees) but have not launched digital SCF platforms. Two fintech startups have entered the market with invoice discounting products, but neither has achieved significant scale. Regional SCF platforms from Singapore and Thailand have not yet expanded into Cambodia, creating a window of opportunity for first movers.\n\nThe optimal market entry strategy depends on the entrant\'s profile. For fintech startups, CamFinTech recommends starting with a marketplace model (Category 2 PSP license) that connects institutional lenders to verified receivables, minimizing capital requirements while building transaction volume and data. For established financial institutions, a direct factoring model (MFI or bank license) offers higher margins and greater control over the credit process but requires significant capital and regulatory compliance investment.\n\nRegardless of model, successful market entry requires three elements: anchor buyer partnerships (securing commitments from 3-5 major garment brands or domestic corporates to approve supplier invoices on the platform), bank partnerships (establishing Bakong integration and potential co-lending arrangements), and GaaP integration (completing CamInvoice, Bakong, CamDigiKey, and CamDX integrations). CamFinTech provides strategic advisory and technical consulting across all three elements, leveraging our relationships with anchor corporates, banking partners, and regulatory bodies to accelerate market entry.',
    },
    {
      heading: 'Risks and Mitigation Strategies',
      content: 'Investors and operators should carefully assess the risks associated with Cambodia\'s SCF market. Credit risk remains the primary concern: Cambodia\'s credit bureau coverage is limited, historical default data for SCF products is sparse, and the legal framework for enforcing receivables assignments is untested in court. Mitigation strategies include focusing on investment-grade international buyers, obtaining credit insurance from multilateral institutions (IFC, ADB), and structuring first-loss guarantees with anchor corporates.\n\nRegulatory risk is moderate but manageable. The NBC\'s evolving approach to SCF regulation could result in new licensing requirements or capital adequacy rules that increase compliance costs. Close engagement with the NBC through formal consultation processes and industry associations reduces this risk. CamFinTech maintains ongoing regulatory dialogue on behalf of our SCF clients.\n\nOperational risk centers on GaaP infrastructure reliability. CamInvoice, as the newest platform layer, has experienced occasional processing delays during peak periods. SCF platforms should implement graceful degradation that allows manual invoice verification when the API is unavailable. Currency risk is relevant for USD-denominated SCF programs, as the NBC\'s de-dollarization policy could increase FX costs over time. Macro-economic risk is mitigated by Cambodia\'s strong GDP growth trajectory (6.1% projected for 2026) and diversifying export base.\n\nCamFinTech provides comprehensive risk assessment and mitigation consulting for SCF investors and operators, drawing on our deep understanding of Cambodia\'s regulatory, economic, and technological landscape.',
    },
  ],
};
